Repository Team-Mercury-s-Final-Project/Star-FE, pull requests merged in 2025-02, with the labels that each got.

#41 axios 를 통한 jwt 필터 적용
  src/api.js
  src/pages/GroupDetailModal.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupFormModal.vue
  src/pages/GroupList.vue
  src/pages/HomePage.vue
  src/pages/NextPage.vue
  src/pages/TestPage.vue
  src/router/index.js
Labels: refactoring

#47 버그픽스-공지사항 추가 관련
  src/pages/GroupDetailModal.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupList.vue
Labels: bug

#53 1. 액세스 토큰 재 발행
  package.json
  src/App.vue
  src/api/authentication.js
  src/api/axiosInstance.js
  src/api/axiosInstance_test.js
  src/components/Header.vue
  src/components/modal/LoginPermissionRequired.vue
  src/pages/Userinfo.vue
  src/router/index.js
  src/store/store.js
Labels: feat

#58 버그 수정 완료
  src/components/Sidebar.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupFormModal.vue
Labels: bug

#59 fix: sse 연결 버그 해결
  src/App.vue
  src/components/UserList.vue
  src/pages/GroupDetailPage.vue
  src/store/store.js
Labels: bug

#61 Feat/#60 enter group
  src/pages/GroupDetailPage.vue
Labels: feat

#65 Feat/#63 hide if not host
  src/pages/GroupDetailPage.vue
Labels: design

#70 타이머 페이지 러프디자인
  src/pages/FocusRoomPage2.vue
  src/router/index.js
Labels: design

#71 배포 테스트
  .env
  src/api/authentication.js
  src/api/axiosInstance.js
  src/components/Header.vue
  src/components/Sidebar.vue
  src/components/chat/ChatRoomList.vue
  src/components/modal/UserJoinedGroupModal.vue
  src/pages/ChatRoomList.vue
  src/pages/FocusRoomPage2.vue
  src/pages/GroupDetailPage.vue
  src/pages/Userinfo.vue
  src/router/index.js
  vite.config.js
Labels: infra

#72 Feat/#66 그룹원 정보 모달 추가 & 그룹 닉네임 변경 기능 구현
  src/components/UserList.vue
  src/components/UserModal.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupList.vue
Labels: feat

#75 Feat/#73 타이머 채팅방 페이지 sse 연결
  src/App.vue
  src/components/UserModal.vue
  src/pages/GroupDetailPage.vue
  src/router/index.js
Labels: feat

#77 디자인 변경
  src/App.vue
  src/pages/FocusRoomPage2.vue
  src/pages/GroupDetailPage.vue
Labels: design

#83 feat: SSE 집중방 인원 수 조회
  src/App.vue
  src/pages/GroupDetailPage.vue
Labels: feat

#85 fix: 사용자 상태 표시 개선
  src/App.vue
  src/components/UserList.vue
  src/pages/GroupDetailPage.vue
Labels: bug

#87 fix: 에러 수정
  src/components/UserList.vue
Labels: bug

#94 Feat/#84 랭킹 기능그룹 랭킹 api 반영
  src/assets/refresh-black.svg
  src/assets/refresh-ccw.svg
  src/pages/FocusRoomPage.vue
  src/pages/GroupDetailPage.vue
Labels: feat

#99 채팅방 마이너한 변경, 채팅 리스트 변경
  src/components/Header.vue
  src/components/chat/ChatRoom.vue
  src/components/chat/ChatRoomList.vue
  src/pages/GroupDetailPage.vue
Labels: design

#100 채팅방 및 채팅리스트 변경사항 적용
  src/components/Header.vue
  src/components/chat/ChatRoom.vue
  src/components/chat/ChatRoomList.vue
  src/pages/GroupDetailPage.vue
Labels: design

#102 feat: 내 타이머에 오늘의 랭킹 반영
  src/components/timer/MyTimer.vue
  src/pages/FocusRoomPage.vue
Labels: bug, feat

#103 내 타이머에 랭킹 반영
  src/components/timer/MyTimer.vue
  src/pages/FocusRoomPage.vue
Labels: bug, feat

#111 refactor: MyTimer에서 setInterval 대신 setTimeout 사용
  src/components/timer/MyTimer.vue
Labels: bug, refactoring

#114 Refactor/#108 타이머 시간 증가 함수 변경
  src/components/timer/GroupMemberTimer.vue
  src/components/timer/MyTimer.vue
Labels: refactoring
