Repository Team-Mercury-s-Final-Project/Star-FE, pull requests merged in 2025-01, with the labels that each got.

#4 design: 헤더 사이드바 유져 디자인 변경
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/style.css
  src/components/Header.vue
  src/components/HelloWorld.vue
  src/components/Sidebar.vue
  src/components/UserList.vue
  src/main.js
  src/style.css
  src/styles/style.css
Labels: design

#11 router test 완료
  src/App.vue
  src/components/Header.vue
  src/main.js
  src/pages/HomePage.vue
  src/pages/NextPage.vue
  src/router/index.js
Labels: infra

#15 design: 그룹 디테일 페이지 완성, 연결 대기중;
  src/pages/GroupDetailPage.vue
  src/pages/HomePage.vue
  src/pages/NextPage.vue
  src/router/index.js
Labels: design

#26 모달 완성 및 연결 완료
  .gitignore
  package-lock.json
  src/pages/GroupDetailPage.vue
  src/pages/NextPage.vue
  src/router/index.js
Labels: feat, design

#28 Feat/#19 그룹 리스트 페이지
  src/App.vue
  src/pages/GroupList.vue
  src/router/index.js
Labels: feat

#29 refactor: 그룹 정보 표시 내용 수정
  src/pages/GroupList.vue
Labels: refactoring

#31 feat: 그룹 정보 모달 & 가입 기능
  src/pages/GroupDetailModal.vue
  src/pages/GroupList.vue
Labels: feat
